alert('hai sayang')
alert('gimana kabarnya? sehatkan.')
alert('sekarang lagi ultah ya.... Hehehe')
alert('aku Lupa deh umur kamu berapa sih sekarang?')
prompt('Coba isi disini dong aku lupa???')
alert('Hehehe.... engga kok aku bercanda dong itu')
alert('semoga panjang umur ya sayang')
alert('semoga apapun keingin kamu terkabul semua,ya sayang')
alert('semoga rezekinya di tahun ini makin dilancarin')
alert('Maaf ya belom bisa ngasih apa-apa ke kamu')
alert('ya pokonya semoga di bertambah nya umur kamu sekarang')
alert('Kamu menjadi pribadi yang lebih baik lagi ya sayang ')
alert('I LOVE you BY')
